esphome:
  name: neopixel_esp01

esp8266:
  board: esp01_1m

external_components:
  - source:
      type: local
      path: "./components/ring_controller"
    components: [ring_controller]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
logger:

light:
  - platform: ring_controller
    id: ring
    name: "NeoPixel Ring"

select:
  - platform: ring_controller
    id: neopixel_effect
    name: "Effetto Anello"

number:
  - platform: ring_controller
    id: neopixel_speed
    name: "Velocità Effetto"

  - platform: ring_controller
    id: neopixel_intensity
    name: "Intensità Effetto"
